apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-deployer-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: argocd-deployer
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-server
  apiGroup: rbac.authorization.k8s.io
