apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sboms.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                sbom:
                  type: string
  scope: Namespaced
  names:
    plural: sboms
    singular: sbom
    kind: SBOM
    shortNames:
    - sb
