name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t vinayak868/simple-node-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push vinayak868/simple-node-app:latest

    - name: Generate SBOM
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft . -o cyclonedx-json > sbom.json

    - name: Commit SBOM to repo
      run: |
        git config --global user.name 'vinatu'
        git config --global user.email 'l00179000@atu.ie'
        git add sbom.json
        git commit -m 'Add SBOM'
        git push

    - name: Verify Compliance
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
        grype sbom:sbom.json -o json > compliance-report.json

    - name: Commit Compliance Report to repo
      run: |
        git config --global user.name 'vinatu'
        git config --global user.email 'l00179000@atu.ie'
        git add compliance-report.json
        git commit -m 'Add Compliance Report'
        git push
